##this to configue just the user and the password and the port and the path that we work with 



[mysqld]
user= root

datatdir=/var/lib/mysql

port=3306 //conection port

innodb_buffer_pool_size=256M //performance tuning


character-set-server=utf8mb4 //this is important for wordpress "encoding"
 
bind-address=0.0.0.0 // this is mean the mariadb shulld listening from all the host all the networks
