##this all the config nginx have https://nginx.org/en/docs/http/configuring_https_servers.html
#youtube part  https://www.youtube.com/watch?v=J9jKKeV1XVE&t=301s
worker_processes auto;
events {

}
http {
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;

    server {
        listen              443 ssl;
        server_name         localhost;
        keepalive_timeout   70;

        ssl_certificate     /etc/nginx/certs/www.example.com.crt;
        ssl_certificate_key /etc/nginx/certs/www.example.com.key;
        ssl_protocols       TLSv1.2 TLSv1.3;
        # ssl_ciphers         HIGH:!aNULL:!MD5;
        root /var/www/html;
        index index.php index.html;
        ## !!!! NGINX talks to PHP-FPM using fastcgi, NOT proxy_pass
        location ~ \.php$ {
            fastcgi_pass wordpress:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }
    #this server is for proxy
    # server{
    #     listen 80;
    #     location /simple{ #this is just exemple of simple we can change it liter
    #         proxy_pass https://localhost:8080/simple/;
    #     }
    # }
}