services:
  nginx:
    image: nginx:inception
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wp_volume:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  mariadb:
    image: mariadb:inception
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ADMIN_PASSWORD_FILE: /run/secrets/credentials
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_password
      - db_root_password
      - credentials
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    image: wordpress:inception
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - wp_volume:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/maskour/data/mariadb

  wp_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/maskour/data/wordpress

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt