#this file us to ordered the automate the creat of the doker image as a list of the commands 
#each iinstruction in the file creat a new layer in the image

FROM debian;lstes
WORKDIR /the/workdir/path
COPY source dest
RUN command
CMD [ "executable" ]
EXPOSE 8080
